name: TDS se bachalo

on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:

jobs:
  tds-paglu:
    runs-on: ubuntu-slim
    steps:
      - name: 24f2008341@ds.study.iitm.ac.in
        run: echo "Hello World!"
